<a href="https://colab.research.google.com/github/Harish26242002/Data-Science-Portfolio/blob/main/Bret_Model(random%20seed(42)).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

data ="i like data science and machine learning",
np.random.seed(42),
final_attention_matrix

In [26]:
data = "i like data science and machine learning"
tokens = data.split()
tokens

['i', 'like', 'data', 'science', 'and', 'machine', 'learning']

In [27]:
np.random.seed(42)

In [28]:
num_tokens = len(tokens)
embedding_dim = 10


In [29]:
embeddings = np.random.randint(0, 10, (num_tokens, embedding_dim)) / 10
embeddings

array([[0.6, 0.3, 0.7, 0.4, 0.6, 0.9, 0.2, 0.6, 0.7, 0.4],
       [0.3, 0.7, 0.7, 0.2, 0.5, 0.4, 0.1, 0.7, 0.5, 0.1],
       [0.4, 0. , 0.9, 0.5, 0.8, 0. , 0.9, 0.2, 0.6, 0.3],
       [0.8, 0.2, 0.4, 0.2, 0.6, 0.4, 0.8, 0.6, 0.1, 0.3],
       [0.8, 0.1, 0.9, 0.8, 0.9, 0.4, 0.1, 0.3, 0.6, 0.7],
       [0.2, 0. , 0.3, 0.1, 0.7, 0.3, 0.1, 0.5, 0.5, 0.9],
       [0.3, 0.5, 0.1, 0.9, 0.1, 0.9, 0.3, 0.7, 0.6, 0.8]])

In [30]:
d_k = 4

wq = np.random.randint(0, 10, (embedding_dim, d_k)) / 10
wk = np.random.randint(0, 10, (embedding_dim, d_k)) / 10
wv = np.random.randint(0, 10, (embedding_dim, d_k)) / 10


In [31]:
Q = np.dot(embeddings, wq)
K = np.dot(embeddings, wk)
V = np.dot(embeddings, wv)


In [32]:
Q

array([[2.31, 2.37, 2.69, 2.73],
       [1.96, 2.26, 2.21, 2.12],
       [1.91, 2.4 , 2.8 , 2.23],
       [2.12, 2.23, 2.12, 2.  ],
       [2.25, 2.28, 2.93, 2.66],
       [1.35, 1.69, 1.81, 1.24],
       [2.65, 2.33, 2.68, 2.64]])

In [33]:
K

array([[2.15, 2.92, 2.5 , 2.62],
       [1.57, 2.14, 2.5 , 2.21],
       [1.79, 2.89, 2.44, 2.24],
       [1.28, 2.36, 2.57, 2.18],
       [2.29, 3.1 , 2.4 , 2.79],
       [1.88, 2.06, 1.63, 1.97],
       [2.04, 2.94, 2.01, 2.41]])

In [34]:
V

array([[2.39, 1.93, 2.07, 1.6 ],
       [2.12, 1.6 , 1.53, 1.29],
       [2.78, 1.63, 1.52, 1.4 ],
       [2.2 , 1.65, 1.65, 1.45],
       [2.96, 2.44, 2.2 , 1.91],
       [1.56, 1.63, 1.64, 1.22],
       [2.14, 1.82, 1.56, 1.24]])

In [35]:
scores = np.dot(Q, K.T)
scaled_scores = scores / np.sqrt(d_k)


In [36]:
def softmax(x):
    e_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e_x / e_x.sum(axis=1, keepdims=True)


In [37]:

attention_weights = softmax(scaled_scores)

In [38]:
final_attention_matrix = np.dot(attention_weights, V)

In [39]:
final_attention_matrix


array([[2.63728873, 2.09662155, 1.98945844, 1.66598209],
       [2.60539192, 2.06016434, 1.95541567, 1.6368124 ],
       [2.61724187, 2.06750964, 1.96529993, 1.64601006],
       [2.60405248, 2.06037555, 1.95496363, 1.63600155],
       [2.63361592, 2.09032895, 1.98600429, 1.66296127],
       [2.53767911, 1.98574845, 1.88991936, 1.5813362 ],
       [2.641515  , 2.10337015, 1.99508918, 1.67034992]])